export const SITE_CONFIG = {
  name: "PT Mitra Kreasi Bersama",
  shortName: "MKB",
  tagline: "Mitra Strategis Manpower & Brand Activation FMCG",
  description:
    "PT Mitra Kreasi Bersama adalah perusahaan manpower outsourcing dan brand activation terpercaya untuk sektor FMCG di Indonesia sejak 2009. Didukung teknologi JUPITER untuk real-time field reporting.",
  url: "https://mitrakreasibersama.com",
  email: "info@mitrakreasibersama.com",
  phone: "+62 21 1234 5678",
  whatsapp: "6281234567890",
  address: "Jakarta, Indonesia",
  foundedYear: 2009,
  experienceYears: 17,
} as const;

export const NAV_LINKS = [
  { href: "/", label: "Beranda" },
  { href: "/about", label: "Tentang Kami" },
  { href: "/services", label: "Layanan" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/technology", label: "JUPITER" },
  { href: "/clients", label: "Klien" },
  { href: "/coverage", label: "Coverage" },
  { href: "/contact", label: "Kontak" },
] as const;

export const PROJECTS = [
  {
    slug: "sido-muncul-smd-spg",
    client: "Sido Muncul",
    title: "SMD & SPG Regular",
    service: "SPG & Merchandiser",
    serviceId: "spg",
    area: "Multi-area",
    brands: ["Sido Muncul"],
    cover: "/company/portfolio/covers/sido-muncul.webp",
    overview: "/company/portfolio/overviews/sido-muncul.webp",
    featured: true,
  },
  {
    slug: "hatari-spg-national",
    client: "ASW Foods",
    title: "SPG Regular MT & GT",
    service: "SPG",
    serviceId: "spg",
    area: "Nasional",
    brands: ["Hatari"],
    cover: "/company/portfolio/covers/hatari.webp",
    overview: "/company/portfolio/overviews/hatari.webp",
    featured: true,
  },
  {
    slug: "sinarmas-spg-instore",
    client: "Sinarmas",
    title: "Regular & Event SPG Instore Promo",
    service: "SPG & Brand Activation",
    serviceId: "brand-activation",
    area: "Nasional",
    brands: ["Filma", "Pristine", "ZODA"],
    cover: "/company/portfolio/covers/sinarmas.webp",
    overview: "/company/portfolio/overviews/sinarmas.webp",
  },
  {
    slug: "marimas-smd-motorist",
    client: "Marimas",
    title: "SMD & Sales Motorist",
    service: "Merchandiser & Sales Motorist",
    serviceId: "sales-motorist",
    area: "Jabodetabek, Jawa Tengah, Jawa Barat, Jawa Timur, Bali",
    brands: ["Marimas", "Herbal Ice"],
    cover: "/company/portfolio/covers/marimas.webp",
    overview: "/company/portfolio/overviews/marimas.webp",
    featured: true,
  },
  {
    slug: "kalbe-spreading-motorist-2023",
    client: "Kalbe Consumer Health",
    title: "Spreading Team Motorist 2023",
    service: "Sales Motorist",
    serviceId: "sales-motorist",
    area: "Nasional",
    brands: ["Kalbe"],
    cover: "/company/portfolio/covers/kalbe-motorist.webp",
    overview: "/company/portfolio/overviews/kalbe-motorist.webp",
    highlights: [
      "Target 200 motorist",
      "445.771 total call",
      "307.080 effective call",
      "Rp12,2 miliar total value YTD",
    ],
    featured: true,
  },
  {
    slug: "fiesta-motorist",
    client: "Fiesta",
    title: "Motorist Channel Execution",
    service: "Sales Motorist",
    serviceId: "sales-motorist",
    area: "Jabodetabek",
    brands: ["Champ", "Akumo", "Asimo", "Fiesta"],
    cover: "/company/portfolio/covers/fiesta-motorist.webp",
    overview: "/company/portfolio/overviews/fiesta-motorist.webp",
  },
  {
    slug: "paseo-national-field-force",
    client: "Paseo",
    title: "Regular SPG, MD & Team Leader",
    service: "SPG & Merchandiser",
    serviceId: "merchandiser",
    area: "Nasional",
    brands: ["Paseo"],
    cover: "/company/portfolio/covers/paseo.webp",
    overview: "/company/portfolio/overviews/paseo.webp",
    highlights: ["695 manpower"],
    featured: true,
  },
  {
    slug: "wardah-regular-beauty-advisor",
    client: "Wardah",
    title: "Regular Beauty Advisor",
    service: "Beauty Advisor",
    serviceId: "beauty-advisor",
    area: "Jabodetabek, Jawa Tengah, Jawa Barat",
    brands: ["Wardah"],
    cover: "/company/portfolio/covers/wardah.webp",
    overview: "/company/portfolio/overviews/wardah.webp",
    featured: true,
  },
  {
    slug: "danone-regular-merchandiser",
    client: "Danone",
    title: "Regular Merchandiser SAT & IDM",
    service: "Merchandiser",
    serviceId: "merchandiser",
    area: "Jabodetabek",
    brands: ["Milkuat"],
    cover: "/company/portfolio/covers/danone.webp",
    overview: "/company/portfolio/overviews/danone.webp",
  },
  {
    slug: "mayora-national-field-force",
    client: "Mayora",
    title: "Regular SPG, MD & Motorist",
    service: "Integrated Field Force",
    serviceId: "spg",
    area: "Nasional",
    brands: ["All Brand Biscuits"],
    cover: "/company/portfolio/covers/mayora.webp",
    overview: "/company/portfolio/overviews/mayora.webp",
    highlights: ["685 manpower", "Modern Trade & General Trade"],
  },
  {
    slug: "kino-spg-instore",
    client: "Kino",
    title: "Regular & Event SPG Instore Promo",
    service: "SPG & Brand Activation",
    serviceId: "brand-activation",
    area: "Jabodetabek, Jawa Barat",
    brands: ["Sleek", "Absolute"],
    cover: "/company/portfolio/covers/kino.webp",
    overview: "/company/portfolio/overviews/kino.webp",
  },
  {
    slug: "mustika-ratu-beauty-advisor",
    client: "Mustika Ratu",
    title: "Regular Beauty Advisor",
    service: "Beauty Advisor",
    serviceId: "beauty-advisor",
    area: "Jabodetabek, Jawa Tengah, Jawa Timur",
    brands: ["Mustika Ratu"],
    cover: "/company/portfolio/covers/mustika-ratu.webp",
    overview: "/company/portfolio/overviews/mustika-ratu.webp",
    highlights: ["324 manpower"],
  },
  {
    slug: "combiphar-spg-event",
    client: "Combiphar",
    title: "SPG Regular & Instore Event",
    service: "SPG & Brand Activation",
    serviceId: "brand-activation",
    area: "Jabodetabek & Medan",
    brands: ["Prive"],
    cover: "/company/portfolio/covers/combiphar.webp",
    overview: "/company/portfolio/overviews/combiphar.webp",
  },
  {
    slug: "nutrifood-regular-spg",
    client: "Nutrifood",
    title: "Regular SPG Carrefour & Giant",
    service: "SPG",
    serviceId: "spg",
    area: "Jawa Timur, Jabodetabek, Jawa Barat, Jawa Tengah",
    brands: ["WRP", "Heavenly Blush Yogurt"],
    cover: "/company/portfolio/covers/nutrifood.webp",
    overview: "/company/portfolio/overviews/nutrifood.webp",
  },
  {
    slug: "gonusa-spg-modern-trade",
    client: "Gonusa Prima Distribusi",
    title: "SPG Modern Trade Regular",
    service: "SPG",
    serviceId: "spg",
    area: "Jabodetabek",
    brands: ["Milk Life", "Caffino", "Kopi Tubruk Gadjah", "Croissant"],
    cover: "/company/portfolio/covers/gonusa.webp",
    overview: "/company/portfolio/overviews/gonusa.webp",
  },
  {
    slug: "unza-vitalis-sales-motorist",
    client: "Unza Vitalis",
    title: "Sales Motorist",
    service: "Sales Motorist",
    serviceId: "sales-motorist",
    area: "Jabodetabek, Jawa Tengah, Jawa Timur",
    brands: ["Shampoo Romano", "Izzy Parfume"],
    cover: "/company/portfolio/covers/unza-vitalis.webp",
    overview: "/company/portfolio/overviews/unza-vitalis.webp",
  },
  {
    slug: "suntory-sales-canvasser",
    client: "Suntory Garuda",
    title: "Sales Canvasser",
    service: "Sales Canvasser",
    serviceId: "sales-motorist",
    area: "Jabodetabek, Jawa Barat, Jawa Tengah, Jawa Timur",
    brands: ["My Tea", "Goodmood", "Okky Jelly"],
    cover: "/company/portfolio/covers/suntory-canvasser.webp",
    overview: "/company/portfolio/overviews/suntory-canvasser.webp",
    highlights: ["34 team", "General Trade"],
  },
  {
    slug: "myroti-merchandiser-minimarket",
    client: "Yamazaki Indonesia",
    title: "Merchandiser Minimarket",
    service: "Merchandiser",
    serviceId: "merchandiser",
    area: "Jabodetabek, Jawa Barat, Jawa Tengah",
    brands: ["MyRoti"],
    cover: "/company/portfolio/covers/myroti.webp",
    overview: "/company/portfolio/overviews/myroti.webp",
  },
  {
    slug: "filma-spread-challenge",
    client: "Filma",
    title: "Margarine Spread Challenge",
    service: "Instore Activation",
    serviceId: "brand-activation",
    area: "Hypermart Jabodetabek",
    brands: ["Filma"],
    cover: "/company/portfolio/covers/filma-activation.webp",
    overview: "/company/portfolio/overviews/filma-activation.webp",
    highlights: ["Spread challenge", "Baking demo", "Push selling"],
  },
  {
    slug: "okky-school-to-school",
    client: "Suntory Garuda",
    title: "Okky Jelly School-to-School",
    service: "Brand Activation",
    serviceId: "brand-activation",
    area: "Sekolah",
    brands: ["Okky Jelly Drink Big"],
    cover: "/company/portfolio/covers/okky-school.webp",
    overview: "/company/portfolio/overviews/okky-school.webp",
    featured: true,
  },
] as const;

export const SERVICES = [
  {
    id: "spg",
    title: "Sales Promotion Girl (SPG)",
    shortTitle: "SPG",
    description:
      "Tim SPG profesional yang terlatih untuk meningkatkan brand awareness dan mendorong konversi penjualan di outlet ritel modern maupun tradisional.",
    icon: "Users",
    features: [
      "Rekrutmen & training standar brand",
      "Penampilan & product knowledge terukur",
      "Reporting penjualan harian",
      "Supervisi lapangan berjenjang",
    ],
  },
  {
    id: "merchandiser",
    title: "Merchandiser",
    shortTitle: "Merchandiser",
    description:
      "Pengelolaan display, stock, dan visibility produk di toko agar shelf share optimal dan planogram brand terpenuhi secara konsisten.",
    icon: "Package",
    features: [
      "Planogram compliance",
      "Stock check & replenishment",
      "Foto display via JUPITER",
      "Coverage outlet terjadwal",
    ],
  },
  {
    id: "beauty-advisor",
    title: "Beauty Advisor",
    shortTitle: "Beauty Advisor",
    description:
      "Beauty advisor berpengalaman untuk kategori personal care & cosmetics, siap memberikan edukasi produk dan meningkatkan trial & purchase.",
    icon: "Sparkles",
    features: [
      "Product consultation",
      "Demo & sampling terarah",
      "CRM & follow-up pelanggan",
      "KPI penjualan terpantau",
    ],
  },
  {
    id: "sales-motorist",
    title: "Sales Motorist",
    shortTitle: "Sales Motorist",
    description:
      "Armada sales motorist untuk distribusi dan penjualan langsung ke toko-toko tradisional, warung, dan saluran modern trade di wilayah target.",
    icon: "Bike",
    features: [
      "Route planning optimal",
      "Order taking & delivery support",
      "GPS tracking lapangan",
      "Target & achievement dashboard",
    ],
  },
  {
    id: "brand-activation",
    title: "Brand Activation",
    shortTitle: "Brand Activation",
    description:
      "Eksekusi event, sampling, roadshow, dan aktivasi brand multi-channel yang terukur, terkoordinasi, dan dilengkapi dokumentasi real-time.",
    icon: "Megaphone",
    features: [
      "Konsep & eksekusi event",
      "Sampling campaign",
      "Roadshow nasional",
      "Laporan performa aktivasi",
    ],
  },
] as const;

export const CLIENTS = [
  { name: "Sido Muncul", logo: "/company/clients/sido-muncul.webp", ongoing: true },
  { name: "Hatari", logo: "/company/clients/hatari.webp", ongoing: true },
  { name: "Marimas", logo: "/company/clients/marimas.webp", ongoing: true },
  { name: "Suntory Garuda", logo: "/company/clients/suntory-garuda.webp", ongoing: true },
  { name: "Kalbe", logo: "/company/clients/kalbe.webp", ongoing: true },
  { name: "Fiesta", logo: "/company/clients/fiesta.webp", ongoing: true },
  { name: "Sinarmas", logo: "/company/clients/sinarmas.webp", ongoing: true },
  { name: "MyRoti", logo: "/company/clients/myroti.webp" },
  { name: "Combiphar", logo: "/company/clients/combi-phar.webp" },
  { name: "Wardah", logo: "/company/clients/wardah.webp" },
  { name: "Garudafood", logo: "/company/clients/garudafood.webp" },
  { name: "Mayora", logo: "/company/clients/mayora.webp" },
  { name: "Kino", logo: "/company/clients/kino.webp" },
  { name: "Paseo", logo: "/company/clients/paseo.webp" },
  { name: "Mecosin", logo: "/company/clients/mecosin.webp" },
  { name: "Mustika Ratu", logo: "/company/clients/mustika-ratu.webp" },
  { name: "SOYJOY", logo: "/company/clients/soyjoy.webp" },
  { name: "Gonusa Prima Distribusi", logo: "/company/clients/gonusa.webp" },
  { name: "Nabati", logo: "/company/clients/nabati.webp" },
  { name: "Landson", logo: "/company/clients/landson.webp" },
  { name: "Darya-Varia", logo: "/company/clients/darya-varia.webp" },
  { name: "Unza Vitalis", logo: "/company/clients/unza-vitalis.webp" },
  { name: "Quaker", logo: "/company/clients/quaker.webp" },
  { name: "Ichitan", logo: "/company/clients/ichitan.webp" },
  { name: "Danone", logo: "/company/clients/danone.webp" },
  { name: "Pigeon", logo: "/company/clients/pigeon.webp" },
  { name: "Wook", logo: "/company/clients/wook.webp" },
  { name: "Shinzui", logo: "/company/clients/shinzui.webp" },
  { name: "3M", logo: "/company/clients/3m.webp" },
  { name: "Reckitt", logo: "/company/clients/reckitt.webp" },
] as const;

export const OFFICE_LOCATIONS = [
  {
    name: "Tangerang Selatan",
    type: "Representative Office",
    address:
      "Jl. Delima Jaya No. 1A, RT.1/RW.2, Rempoa, Kec. Ciputat Timur, Kota Tangerang Selatan, Banten 15412",
    lat: -6.3004,
    lng: 106.7544,
    photo: "/company/offices/tangerang-selatan.webp",
  },
  {
    name: "Medan",
    type: "Representative Office",
    address: "Jl. Eka Rasmi No. 49A, Medan Johor, Medan",
    lat: 3.5354,
    lng: 98.6772,
    photo: "/company/offices/medan.webp",
  },
  {
    name: "Bandung",
    type: "Representative Office",
    address: "Griya Caraka Blok G No. 35, Antapani, Bandung",
    lat: -6.9147,
    lng: 107.6627,
    photo: "/company/offices/bandung.webp",
  },
  {
    name: "Semarang",
    type: "Representative Office",
    address: "Jl. Pudak Payung Asri 1 No. 6, Pudak Payung, Semarang",
    lat: -7.0882,
    lng: 110.4093,
    photo: "/company/offices/semarang.webp",
  },
  {
    name: "Surabaya",
    type: "Representative Office",
    address: "Perum Taman Wiguna Selatan XI/2, Rungkut, Surabaya",
    lat: -7.3265,
    lng: 112.7818,
    photo: "/company/offices/surabaya.webp",
  },
  {
    name: "Palembang",
    type: "Homebase",
    address:
      "Komp. Vila Gardena 3 Blok F No. 7, Kec. Alang-Alang Lebar, Palembang",
    lat: -2.9387,
    lng: 104.7048,
  },
  {
    name: "Banjarmasin",
    type: "Homebase",
    address:
      "Jl. Cempaka Putih, Belakang Masjid Nurul RT 08 No. 19, Kel. Kebun Bunga, Banjarmasin Timur",
    lat: -3.3068,
    lng: 114.6155,
  },
  {
    name: "Makassar",
    type: "Homebase",
    address:
      "Jl. Kimia 8, Kav. SS 19, Kawasan Industri Makassar, Makassar, Sulawesi Selatan",
    lat: -5.1039,
    lng: 119.4938,
  },
  {
    name: "Bali",
    type: "Homebase",
    address:
      "Banjar Tegal Luwih, Blok SS12A, Dalung Permai, Kuta Utara, Badung",
    lat: -8.6252,
    lng: 115.1728,
  },
] as const;

export const COVERAGE_CITIES = [
  { name: "Jakarta", lat: -6.2088, lng: 106.8456, region: "Jabodetabek", teamSize: "500+" },
  { name: "Bandung", lat: -6.9175, lng: 107.6191, region: "Jawa Barat", teamSize: "150+" },
  { name: "Surabaya", lat: -7.2575, lng: 112.7521, region: "Jawa Timur", teamSize: "200+" },
  { name: "Medan", lat: 3.5952, lng: 98.6722, region: "Sumatera Utara", teamSize: "100+" },
  { name: "Semarang", lat: -6.9667, lng: 110.4167, region: "Jawa Tengah", teamSize: "120+" },
  { name: "Makassar", lat: -5.1477, lng: 119.4327, region: "Sulawesi Selatan", teamSize: "80+" },
  { name: "Palembang", lat: -2.9761, lng: 104.7754, region: "Sumatera Selatan", teamSize: "70+" },
  { name: "Denpasar", lat: -8.6705, lng: 115.2126, region: "Bali", teamSize: "60+" },
  { name: "Yogyakarta", lat: -7.7956, lng: 110.3695, region: "DI Yogyakarta", teamSize: "50+" },
  { name: "Balikpapan", lat: -1.2379, lng: 116.8529, region: "Kalimantan Timur", teamSize: "40+" },
  { name: "Manado", lat: 1.4748, lng: 124.8421, region: "Sulawesi Utara", teamSize: "30+" },
  { name: "Pekanbaru", lat: 0.5071, lng: 101.4478, region: "Riau", teamSize: "45+" },
] as const;

export const WHY_US = [
  {
    title: "Kepercayaan 17+ Tahun",
    description:
      "Sejak 2009, MKB telah dipercaya brand-brand besar FMCG di Indonesia untuk mengelola tenaga lapangan dan aktivasi merek.",
    icon: "ShieldCheck",
  },
  {
    title: "Teknologi JUPITER",
    description:
      "Sistem proprietary real-time field reporting yang memberi visibilitas penuh atas aktivitas, attendance, dan performa di lapangan.",
    icon: "Cpu",
  },
  {
    title: "Skala Nasional",
    description:
      "Jaringan operasional yang menjangkau kota-kota utama di seluruh Indonesia dengan tim lokal yang siap di-deploy.",
    icon: "MapPin",
  },
  {
    title: "Kepatuhan Operasional",
    description:
      "Proses rekrutmen, payroll, BPJS, dan SOP lapangan yang rapi, terukur, dan siap diaudit klien enterprise.",
    icon: "FileCheck",
  },
] as const;

export const JUPITER_FEATURES = [
  {
    title: "Real-time Attendance",
    description:
      "Absensi GPS, geo-fencing, dan foto selfie untuk memastikan kehadiran tim di lokasi yang benar.",
    icon: "Clock",
  },
  {
    title: "Field Activity Reporting",
    description:
      "Laporan kunjungan, merchandising, penjualan, dan foto display terkirim secara real-time ke dashboard.",
    icon: "ClipboardList",
  },
  {
    title: "Live Dashboard",
    description:
      "Pantau KPI, coverage, dan achievement per wilayah, brand, maupun individu dalam satu layar.",
    icon: "LayoutDashboard",
  },
  {
    title: "Photo & Evidence Capture",
    description:
      "Dokumentasi visual planogram, POSM, dan kondisi rak dengan timestamp dan koordinat lokasi.",
    icon: "Camera",
  },
  {
    title: "Route & Coverage Tracking",
    description:
      "Lacak rute sales motorist dan merchandiser untuk optimalisasi coverage dan efisiensi kunjungan.",
    icon: "Route",
  },
  {
    title: "Export & Client Access",
    description:
      "Data siap diekspor dan dibagikan ke stakeholder klien dengan hak akses yang terkontrol.",
    icon: "Share2",
  },
] as const;

export const STATS = [
  { value: "17+", label: "Tahun Pengalaman" },
  { value: "1000+", label: "Tenaga Lapangan" },
  { value: "30+", label: "Kota Coverage" },
  { value: "50+", label: "Brand Partner" },
] as const;

export const MILESTONES = [
  {
    year: "2009",
    title: "Berdiri",
    description: "PT Mitra Kreasi Bersama didirikan di Jakarta dengan fokus manpower SPG & merchandiser.",
  },
  {
    year: "2014",
    title: "Ekspansi Nasional",
    description: "Memperluas jangkauan operasional ke kota-kota utama di Jawa, Sumatera, dan Sulawesi.",
  },
  {
    year: "2018",
    title: "JUPITER Launch",
    description: "Meluncurkan sistem proprietary JUPITER untuk real-time field reporting & monitoring.",
  },
  {
    year: "2022",
    title: "Enterprise Scale",
    description: "Menangani multi-brand national campaign dengan ribuan personel di lapangan.",
  },
  {
    year: "2026",
    title: "Digital Excellence",
    description: "Penguatan platform digital, compliance, dan partner ecosystem untuk klien FMCG.",
  },
] as const;
